name: "Python"

on:
  push:
    branches: [ "develop" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10 for Slam and Novella
      uses: actions/setup-python@v2
      with: { python-version: "3.10" }
    - name: Install tooling
      run: python -m venv .tooling && .tooling/bin/pip install slam-cli==1.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - name: Install package and dev dependencies
      run: .tooling/bin/slam install --no-venv-check
    - name: Run tests
      run: .tooling/bin/slam test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10 for Slam and Novella
      uses: actions/setup-python@v2
      with: { python-version: "3.10" }
    - name: Install tooling
      run: pip install slam-cli==1.0.0 novella==0.1.2 mkdocs mkdocs-material
    - name: Build documentation
      run: cd docs && novella
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/_site

  docs-publish:
    needs: [ test, docs ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: docs
        path: docs/_site
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: rosensteinniklas@gmail.com
        build_dir: docs/_site
